name: Prepare PR to merge

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
    branches:
      - hml	

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-cache-${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci
  
  lint-and-test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        task: ['biome', 'typecheck', 'coverage', 'chromatic']
      fail-fast: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-cache-${{ runner.os }}-

      - name: Run Biome checker
        if: matrix.task == 'biome'
        run: npx biome check ./src

      - name: Run TypeScript Typechecker
        if: matrix.task == 'typecheck'
        run: npx tsc --noEmit

      - name: Run Tests with Coverage
        if: matrix.task == 'coverage'
        run: npm run test:coverage

      - name: Ensure public directory exists
        if: matrix.task == 'chromatic'
        run: mkdir -p public

      - name: Run Chromatic
        if: matrix.task == 'chromatic'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true