# name: release-finalize

# on:
#   push:
#     branches:
#       - master

# jobs:
#   release-finalize:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: googleapis/release-please-action@v4
#         id: release
#         with:
#           token: ${{ secrets.PAT }}
#           config-file: .github/release-please-config.json
#           release-type: node
#           target-branch: master
          
#       - name: Create GitHub Release
#         if: ${{ steps.release.outputs.release_created }}
#         run: |
#           echo "${{ steps.release.outputs.changelog }}" > release-notes.md
#           gh release create ${{ steps.release.outputs.tag_name }} \
#             --title "${{ steps.release.outputs.tag_name }}" \
#             --notes-file release-notes.md
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}